name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.0
<<<<<<< HEAD
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
=======
  firebase_core: ^3.2.0
>>>>>>> 07bab4834e3c6e76dbd58b1da7c9ab684db15c9c
  firebase_database: ^11.0.0
  image_picker: ^0.8.0
  http: ^1.0.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/beep.mp3
